language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
script: 'true'
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: training-bank